#!/bin/zsh

commit_message=$1
local REGEX='^(Add:|Delete:|Feature:|Fix:|Change:|Refactor:|Update:|Doc:)(\S|\s)+.?|^Merge|^Initial Commit'
is_confirm=`echo $commit_message | grep -E "$REGEX"`

if [[ ! $is_confirm ]]; then
	echo "Your commit message doesn't match pattern. Follow the pattern below."
	echo ""
	echo "REGEX Pattern(Type): $REGEX"
	echo ""
	echo "1. <Type: Task Name>"
	echo "2."
	echo "3. <Body: What you cared and how you've changed.>"
	exit 1
fi
