#!/bin/bash
# ブランチ名を commit message 内に埋め込むスクリプト

# ブランチ名取得
branch=$(git branch | grep ^* | sed 's/\* //g')

# first commit前等で、ブランチ名が取れなかった時用
if [ ! $branch ]; then branch='master'; fi

# -m オプションのときも branch 名を出力する
if [ "$2" == "message" ]; then
	printf "$(cat $1)\n\nnote: \nbranch: ${branch}\n" > $1

# -m オプションでないとき
# --amend オプションでは $2 が commit となる
elif [ "$2" != "commit" ]; then
	printf "\n\nnote: \nbranch: ${branch}\n$(cat $1)" > $1
fi
